version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: g2backend_app
    restart: always
    ports:
      - "8010:8080"  
    volumes:
      - .:/app
    command: ["bash", "/app/entrypoint.sh"]
